/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BygdebokerRouteImport } from './routes/bygdeboker'
import { Route as IndexRouteImport } from './routes/index'

const BygdebokerRoute = BygdebokerRouteImport.update({
  id: '/bygdeboker',
  path: '/bygdeboker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bygdeboker': typeof BygdebokerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bygdeboker': typeof BygdebokerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bygdeboker': typeof BygdebokerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bygdeboker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bygdeboker'
  id: '__root__' | '/' | '/bygdeboker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BygdebokerRoute: typeof BygdebokerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bygdeboker': {
      id: '/bygdeboker'
      path: '/bygdeboker'
      fullPath: '/bygdeboker'
      preLoaderRoute: typeof BygdebokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BygdebokerRoute: BygdebokerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
